spring.datasource.url=jdbc:postgresql://dpg-d7bgb92a214c73edpuig-a/song_db_x5nc
spring.datasource.username=song_db_x5nc_user
spring.datasource.password=u6LxAAE5nQKAnCqffUGnnza5ITwgvWgF
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}